# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

create_lazy_vector <- function(mat, dim, idx, getcol, matclass, type) {
    .Call('_LazyAssayVectors_create_lazy_vector', PACKAGE = 'LazyAssayVectors', mat, dim, idx, getcol, matclass, type)
}

